### ISSUE TITLE
Opening new tab in private browsing shares DOM with previous tab while this addon, Tab Mix Plus and Tab Groups addons are installed

### ISSUE THREAD

**Issue by ebugusey** [vovcacik/bug-566510-firefox-addon#6] opened 2016-03-25 11:18 UTC
Firefox 45.0.1
When this addon installed with [Tab Gropus](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama), which is a replacement for Panorama, and [Tab Mix Plus](https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus), there is bugs in private mode of Firefox:
1. Open private mode;
2. Enter some address;
3. Open new tab in private window.

Expected: Private window new tab.
Got: The same tab it was before I tried to open new tab.
![screenshot 2016-03-25 15 17 32](https://cloud.githubusercontent.com/assets/8318227/14043352/ce55e9a8-f29c-11e5-98e2-f01fb26c9548.png)

**Comment by vovcacik** [comment] 2016-04-02 07:33
Hi, I can't reproduce this problem, it works fine for me. Here's what I did:
1. On Windows 8.1 with Firefox 45.0.1 I have created **new firefox profile**
2. I have installed Tab Groups 1.0.2 and Tab Mix Plus 0.4.2.2 and restarted the Firefox
3. Upon Tab Mix Plus request I allowed the built in session manager
4. Then I've opened anonymous window at google.ru
5. **Both `Ctrl+T` and clicking the `+` button simply opened new tab with empty content panel.**

Can you please send detailed steps to reproduce the problem?

**Comment by ebugusey** [comment] 2016-04-02 11:11
I have Windows 7 and Firefox x64 45.0.1. I tried what I did before second time:
1. Created new firefox profile, called it `test bug`.
2. Right away, right from firefox addons tab I installed Tab Groups, Tab Mix Plus and your addon.
3. Restarted firefox by clicking on `Перазпустить сейчас` (that would be `Restart now` in English I think) in addons tab.
4. After restart upon Tab Mix request I selected bult-in session manager.
5. Right after that I opened new private window (is it called anonymous in english version?).
6. Entered `google.ru` in address bar and hit `Enter`.
7. Then I tried to open new tab in this private window and had the same result as before. That is a bug I described earlier.

I'm using russian localization of firefox if that matters. [This one](https://download.mozilla.org/?product=firefox-45.0.1-SSL&os=win64&lang=ru).

**Comment by vovcacik** [comment] 2016-04-03 08:08
I accidently used wrong version of this addon. The bug is reproducible.

**Comment by vovcacik** [comment] 2016-04-03 08:39
There is some major incompatibility between this addon, Tab Mix Plus and Tab Groups. All the addons need to be installed and the issue is limited to private browsing. When you create new tab in private browsing while the current tab has loaded content (_google.ru_ it this case), the new tab has **the very same** content pane linked to it - two tabs share the same DOM.

I won't fix this because
- small number of users exposed to this (all 3 addons need to be installed)
- only private browsing is affected
- it would be very hard to track down the problem, as 3 addons participate on it
- collaboration of all 3 addons would be most likely required to create and maintain the fix

Thanks for reporting this though.

**Closed as completed by vovcacik** 2016-04-03 08:39 UTC
Labels: bug, wontfix

**Comment by ebugusey** [comment] 2016-04-03 12:37
So what do I do now? Should I report this bug to other addons developers?

**Comment by vovcacik** [comment] 2016-04-04 10:18
Yes, you can try to file same issue with the other projects. Link this conversation. But I doubt they will be willing to solve it.

There is no culprit, it is not this addon to cause that problem, neither the others - it is the combination of all 3 addons, that's what makes the issue problematic and hard to fix.

Or you can try to fix it, I can give you some hints, but not the solution.
